[2024-09-21T17:00:20.052+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-21T17:00:20.072+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: localNFLDataIngestionDag.scrape manual__2024-09-21T16:55:45.395890+00:00 [queued]>
[2024-09-21T17:00:20.081+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: localNFLDataIngestionDag.scrape manual__2024-09-21T16:55:45.395890+00:00 [queued]>
[2024-09-21T17:00:20.082+0000] {taskinstance.py:2856} INFO - Starting attempt 8 of 8
[2024-09-21T17:00:20.096+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): scrape> on 2024-09-21 16:55:45.395890+00:00
[2024-09-21T17:00:20.104+0000] {standard_task_runner.py:72} INFO - Started process 599 to run task
[2024-09-21T17:00:20.107+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'localNFLDataIngestionDag', 'scrape', 'manual__2024-09-21T16:55:45.395890+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp8ttqcd3e']
[2024-09-21T17:00:20.109+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask scrape
[2024-09-21T17:00:20.158+0000] {task_command.py:467} INFO - Running <TaskInstance: localNFLDataIngestionDag.scrape manual__2024-09-21T16:55:45.395890+00:00 [running]> on host a38c0324a413
[2024-09-21T17:00:20.242+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='localNFLDataIngestionDag' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T16:55:45.395890+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-21T16:55:45.395890+00:00'
[2024-09-21T17:00:20.244+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-21T17:00:20.245+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-21T17:00:20.246+0000] {logging_mixin.py:190} INFO - Current task name:scrape state:running start_date:2024-09-21 17:00:20.073184+00:00
[2024-09-21T17:00:20.247+0000] {logging_mixin.py:190} INFO - Dag name:localNFLDataIngestionDag and current dag run status:running
[2024-09-21T17:00:20.248+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-21T17:00:20.249+0000] {logging_mixin.py:190} INFO - Current Year: 2024
[2024-09-21T17:00:20.250+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/scrapeNFLData.py", line 13, in scrape_weekly_data
    weekly_data = nfl.import_weekly_data(years=range(current_year_int))
  File "/home/airflow/.local/lib/python3.9/site-packages/nfl_data_py/__init__.py", line 278, in import_weekly_data
    raise ValueError('Data not available before 1999.')
ValueError: Data not available before 1999.
[2024-09-21T17:00:20.262+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-21T17:00:20.263+0000] {logging_mixin.py:190} INFO - Task start:2024-09-21 17:00:20.073184+00:00 end:2024-09-21 17:00:20.262180+00:00 duration:0.188996
[2024-09-21T17:00:20.264+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape> dag:<DAG: localNFLDataIngestionDag> dagrun:<DagRun localNFLDataIngestionDag @ 2024-09-21 16:55:45.395890+00:00: manual__2024-09-21T16:55:45.395890+00:00, state:running, queued_at: 2024-09-21 17:00:18.045613+00:00. externally triggered: True>
[2024-09-21T17:00:20.265+0000] {logging_mixin.py:190} INFO - Failure caused by Data not available before 1999.
[2024-09-21T17:00:20.266+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=localNFLDataIngestionDag, task_id=scrape, run_id=manual__2024-09-21T16:55:45.395890+00:00, execution_date=20240921T165545, start_date=20240921T170020, end_date=20240921T170020
[2024-09-21T17:00:20.278+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-21T17:00:20.279+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task scrape (Data not available before 1999.; 599)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/scrapeNFLData.py", line 13, in scrape_weekly_data
    weekly_data = nfl.import_weekly_data(years=range(current_year_int))
  File "/home/airflow/.local/lib/python3.9/site-packages/nfl_data_py/__init__.py", line 278, in import_weekly_data
    raise ValueError('Data not available before 1999.')
ValueError: Data not available before 1999.
[2024-09-21T17:00:20.321+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-21T17:00:20.345+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-21T17:00:20.349+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
